project/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView

from dock.views import simple_view
from dock.views import boat_list, boat_create, boat_detail, boat_sailor_create
from dock.views import BoatListView, BoatDetailView, BoatCreateView, BoatSailorCreateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('simple/', simple_view, name='simple-view'),
    path('cbv/simple/', TemplateView.as_view(template_name='simple.html'), name='cbv-simple-view'),

    # Views function
    path('boat/', boat_list, name='boat-list'),
    path('boat/<int:pk>/', boat_detail, name='boat-detail'),
    path('boat/create/', boat_create, name='boat-create'),
    path('boat/<int:pk>/sailor/create/', boat_sailor_create, name='boat-sailor-create'),

    # CBV
    path('cbv/boat/', BoatListView.as_view(), name='cbv-boat-list'),
    path('cbv/boat/<int:pk>/', BoatDetailView.as_view(), name='cbv-boat-detail'),
    path('cbv/boat/create/', BoatCreateView.as_view(), name='cbv-boat-create'),
    path('cbv/boat/<int:pk>/sailor/create/', BoatSailorCreateView.as_view(), name='cbv-boat-sailor-create'),
]

dock/models.py
from django.db import models


class Boat(models.Model):

    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    name = models.CharField(max_length=128)

    TYPE_PIROGUE = 'PIROGUE'
    TYPE_EGYPTIAN = 'EGYPTIAN'
    TYPE_GAILLEY = 'GAILLEY'
    TYPE_VIKING = 'VIKING'
    TYPE_GALLEON = 'GALLEON'
    TYPE_GABARRE = 'GABARRE'

    TYPE_CHOICES = (
        (TYPE_PIROGUE, 'Pirogue'),
        (TYPE_EGYPTIAN, 'Égyptien'),
        (TYPE_GAILLEY, 'Galère'),
        (TYPE_VIKING, 'Viking'),
        (TYPE_GALLEON, 'Gallion'),
        (TYPE_GABARRE, 'Gabarre'),
    )
    type = models.CharField(max_length=32, choices=TYPE_CHOICES)


class Sailor(models.Model):

    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    alias = models.CharField(max_length=128, blank=True)

    JOB_CAPTAIN = 'CAPTAIN'
    JOB_SECOND = 'SECOND'
    JOB_GUNNER = 'GUNNER'
    JOB_SAILOR = 'SAILOR'

    JOB_CHOICES = (
        (JOB_CAPTAIN, 'Capitaine'),
        (JOB_SECOND, 'Second'),
        (JOB_GUNNER, 'Canonnier'),
        (JOB_SAILOR, 'Matelot')
    )
    job = models.CharField(max_length=32, choices=JOB_CHOICES)

    boat = models.ForeignKey('dock.Boat', on_delete=models.CASCADE, related_name='crew')

dock/forms.py
from django import forms
from django.core.exceptions import ValidationError

from dock.models import Boat, Sailor


class BoatForm(forms.ModelForm):

    class Meta:
        model = Boat
        fields = ['name', 'type']

    def clean_name(self):
        name = self.cleaned_data['name']
        if name == 'kikool':
            raise ValidationError('Sérieux ?')
        return name


class SailorForm(forms.ModelForm):

    class Meta:
        model = Sailor
        fields = ['first_name', 'last_name', 'alias', 'job']

dock/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView

from dock.models import Boat
from dock.forms import BoatForm, SailorForm


def simple_view(request):
    return HttpResponse('<h1>La vue la plus simple du monde</h1>')


def boat_list(request):
    boats = Boat.objects.all()
    return render(request, 'dock/boat/list.html', {'boats': boats})


class BoatListView(ListView):
    template_name = 'dock/boat/list.html'
    context_object_name = 'boats'
    model = Boat


def boat_create(request):
    if request.method == 'POST':
        form = BoatForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('boat-list'))
    else:
        form = BoatForm()
    return render(request, 'dock/boat/create.html', {'form': form})


class BoatCreateView(CreateView):
    template_name = 'dock/boat/create.html'
    form_class = BoatForm
    success_url = reverse_lazy('cbv-boat-list')


def boat_detail(request, pk):
    boat = Boat.objects.get(pk=pk)
    return render(request, 'dock/boat/detail.html', {'boat': boat})


class BoatDetailView(DetailView):
    template_name = 'dock/boat/detail.html'
    context_object_name = 'boat'
    model = Boat


def boat_sailor_create(request, pk):
    if request.method == 'POST':
        form = SailorForm(request.POST)
        if form.is_valid():
            boat = Boat.objects.get(pk=pk)
            form.instance.boat = boat
            form.save()
            return HttpResponseRedirect(reverse('boat-detail', kwargs={'pk': boat.pk}))
    else:
        form = SailorForm()
    return render(request, 'dock/sailor/create.html', {'form': form})


class BoatSailorCreateView(CreateView):
    template_name = 'dock/sailor/create.html'
    form_class = SailorForm

    def form_valid(self, form):
        form.instance.boat_id = self.kwargs['pk']
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('cbv-boat-detail', kwargs={'pk': self.object.boat.pk})

dock/templates/dock/boat/create.html
{%  extends 'skeleton.html' %}

{% block content %}
    <h1>Nouveau bateau</h1>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Valider">
    </form>
{% endblock content %}

dock/templates/dock/boat/detail.html
{% extends 'skeleton.html' %}

{% block content %}
    <h4>{{ boat.name }}</h4>

    <a href="{% url 'boat-sailor-create' boat.pk %}">Ajouter matelot</a>
    <a href="{% url 'cbv-boat-sailor-create' boat.pk %}" style="color: red">CBV</a>

    <table class="table">
        <thead>
            <tr>
                <th>Prénom</th>
                <th>Nom</th>
                <th>Alias</th>
                <th>Poste</th>
            </tr>
        </thead>
        <tbody>
            {% for sailor in boat.crew.all %}
                <tr>
                    <td>{{ sailor.first_name }}</td>
                    <td>{{ sailor.last_name }}</td>
                    <td>{{ sailor.alias }}</td>
                    <td>{{ sailor.get_job_display }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

dock/templates/dock/boat/list.html
{%  extends 'skeleton.html' %}

{% block content %}
    <h1>Liste des bateaux</h1>

    <a href="{% url 'boat-create' %}">Nouveau bateau</a>
    <a href="{% url 'cbv-boat-create' %}" style="color: red">CBV</a>

    <ul>
        {% for boat in boats %}
            <li>
                <a href="{% url 'boat-detail' boat.pk %}">{{ boat.name }}</a>
                <a href="{% url 'cbv-boat-detail' boat.pk %}" style="color: red">CBV</a>
            </li>
        {% empty %}
            <li>Aucun bateau</li>
        {% endfor %}
    </ul>
{% endblock content %}

dock/templates/dock/sailor/create.html
{%  extends 'skeleton.html' %}

{% block content %}
    <h1>Nouveau matelot</h1>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Valider">
    </form>
{% endblock content %}

dock/templates/skeleton.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django #1</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  </head>
  <body>
    <h1>Gestion du port !</h1>

    <a href="{% url 'boat-list' %}">Accueil Vues fonction</a>
    <a href="{% url 'cbv-boat-list' %}" style="color: red">CBV</a>
    <hr>

    {% block content %}
    {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>

templates/simple.html
<h1>CBV simple</h1>